name: Esteira DevSecOps UNDB - Sucesso Marco

on: [push]

jobs:
  auditoria:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do Repositorio
        uses: actions/checkout@v4

      - name: 2. Preparar Ambiente e Injetar Dependencias
        run: |
          npm install -g snyk snyk-to-html
          python -m pip install --upgrade pip setuptools wheel
          # Usaremos versoes que instalam mas continuam vulneraveis
          echo "django==2.2" > requirements.txt
          echo "requests==2.20.0" >> requirements.txt
          echo "jinja2==2.11.2" >> requirements.txt
          # O '|| true' garante que a esteira continue mesmo com aviso de erro
          pip install -r requirements.txt || true

      - name: 3. Scanner Snyk (Foco em Python)
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          # Adicionamos a flag --package-manager=pip e --file=requirements.txt
          # O comando 'snyk monitor' ajuda o Snyk a mapear melhor as dependencias
          snyk test --file=requirements.txt --package-manager=pip --json > snyk_results.json || echo "{}" > snyk_results.json
          
      - name: 4. Gerar Dashboard do TCC
        if: always()
        run: |
          snyk-to-html -i snyk_results.json -o dashboard_profissional.html

      - name: 5. Upload do Resultado
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Relatorio-Snyk-Final
          path: dashboard_profissional.html