name: Esteira DevSecOps TCC
on: [push]

jobs:
  auditoria:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Baixando o Código
        uses: actions/checkout@v4

      - name: 2. Instalando Ferramentas (Snyk e HTML)
        run: |
          npm install -g snyk snyk-to-html
          pip install bandit django==1.11.29 || true

      - name: 3. Scanner Snyk (Análise de Bibliotecas)
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          # Gera o arquivo de dados bruto (JSON)
          snyk test --json > snyk_results.json

      - name: 4. Criando o Dashboard Profissional
        if: always()
        run: |
          # Transforma o texto bruto no Dashboard colorido que você gosta
          snyk-to-html -i snyk_results.json -o dashboard_snyk_tcc.html

      - name: 5. Scanner Bandit (Análise do Código)
        continue-on-error: true
        run: |
          bandit -r . -f html -o relatorio_bandit.html || true

      - name: 6. Gerando Link de Download
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Resultados-Seguranca-UNDB
          path: |
            dashboard_snyk_tcc.html
            relatorio_bandit.html